### ISSUE TITLE
價格波動&時間的關係

### ISSUE THREAD

**Issue by Will150143** [ChiuAlfredo/options_day_data#12]
選擇權價格波動所用資料的計算方式：(P2-P1)/P1
驗證方法：計算各時段選擇權價格波動的標準差，比較各時段的標準差大小是否存在差異
標準差計算公式
![image](https://github.com/ChiuAlfredo/options_day_data/assets/133984319/b0d7d1cf-8f63-46e5-8113-34561dd4e1ec)

**Comment by Will150143** [comment]
選擇權價格波動所用資料的計算方式：(P2-P1)/P1
驗證方法：計算各時段選擇權價格波動的標準差，比較各時段的標準差大小是否存在差異
標準差計算公式
![image](https://github.com/ChiuAlfredo/options_day_data/assets/133984319/b0d7d1cf-8f63-46e5-8113-34561dd4e1ec)

**Comment by ChiuAlfredo** [comment]
1. 要使用什麼方式做比較價格波動的標準差，完全沒說明
2. (P2-P1)/P1不明確

**Comment by Will150143** [comment]
> 1. 要使用什麼方式做比較價格波動的標準差，完全沒說明
> 2. (P2-P1)/P1不明確

1.如公式所示，可以說一下你指的說明是什麼意思嗎
2.不明確是什麼意思，該分鐘價格-前一分鐘價格/前一分鐘價格，是這樣嗎？
