### ISSUE TITLE
申請OneDrive

### ISSUE THREAD

**Issue by ChiuAlfredo** [ChiuAlfredo/options_day_data#13]
申請完可以幫我填帳號到 #20 當中

**Comment by Will150143** [comment]
- [x]申請onedrive

**Comment by ChiuAlfredo** [comment]
@Will150143 可以直接把onedrive帳號貼過來

**Comment by Will150143** [comment]
> @Will150143 可以直接把onedrive帳號貼過來

![image](https://github.com/ChiuAlfredo/options_day_data/assets/133984319/25589cb8-29bb-46f1-a5bf-4a39564644d6)

**Comment by ChiuAlfredo** [comment]
> > @Will150143 可以直接把onedrive帳號貼過來
> 
> ![image](https://private-user-images.githubusercontent.com/133984319/346322944-25589cb8-29bb-46f1-a5bf-4a39564644d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNDMwODYsIm5iZiI6MTcyMDM0Mjc4NiwicGF0aCI6Ii8xMzM5ODQzMTkvMzQ2MzIyOTQ0LTI1NTg5Y2I4LTI5YmItNDZmMS1hNWJmLTRhMzk1NjQ2NDRkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwODU5NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTcwMGE0OWE1OWUwN2U5ZWM0OTFkZWUxNjM1YTQxOTk2MTk4ZmQwYzQ3ODgwZWMyZjM1YzM1N2JhNDFlNzgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ooqd2IYqG01UWvAWLPSISi81qjM-AA3C0Ta7hhWAxoo)

用複製的😡

**Comment by Will150143** [comment]
luffy150143@gmail.com

**Comment by TsuYiii** [comment]
b11033009@ms.ntust.edu.tw
